### PR TITLE
Output type of min to uint32_t

### PR DESCRIPTION
**Pull request by podaen**

### CODE REVIEW

**Comment by podaen** [comment]
See comment #469

**Comment by seife** [comment]
There is no change in this commit, just an unrelated addition to .gitignore...?

**Comment by podaen** [comment]
I am in transition with my computer and out of reach of my installation. If you are a collaborator you can review it!

**Comment by seife** [comment]
There is nothing to review. The only change in your fork is the addition of the .gitignore file (with totally unrelated stuff).

**Comment by podaen** [comment]
I know, that why I closed it. Thanks for letting me know. Some changed files where not in the commit. I looked at the code once again and found that the issue comes with the SdFat lib when using Fs filesystem. If you are using the core FS lib, you probably not having this issue.

**Pull request closed without merging**
